### ISSUE TITLE
How to manage Unitofwork

### ISSUE THREAD

**Issue by vinayaroraincedo** [JonPSmith/EfCore.GenericServices#11]
I've implement two different service, How to manage unit of work?

Any sample code would be helpful.

**Comment by JonPSmith** [comment]
Hi @vinayaroraincedo,

GenericServices applies a SaveChange after each method - I end the method with `...AndSave` to emphasize that. If you want to call two services then you can either write your own wrapper that calls both services and then you call `SaveChanges`, or if your code is complex you might like to look at [EfCore.GenericBizRunner](https://github.com/JonPSmith/EfCore.GenericBizRunner).
