### ISSUE TITLE
Request transform Nested Properties from Dto to Entity when creating or updating feature

### ISSUE THREAD

**Issue by baoduy** [JonPSmith/EfCore.GenericServices#13]
Let's say, I have a Customer entity as below:

```csharp
[Table("Customers")]
[DisplayName("The Customer")]
public class Customer
{
    public Customer(string name, Contact generalContact = null)
    {
        Name = name;
        Contact = generalContact ?? new Contact();
    }

    private Customer(){}

    public int Id { get; private set; }

    [MaxLength(200)]
    [Required]
    public string Name { get; private set; }

    [Required]
    public Contact Contact { get; private set; }
}

 [Owned]
public class Contact
{
    [MaxLength(200)]
    [Required]
    public string Name { get; set; }
}
```

And Here is my Models
```csharp
public class CustomerDto : ILinkToEntity<Customer>
{
    public int Id { get; set; }

    [MaxLength(200)]
    [Required]
    public string Name { get; set; }

    [Required]
    public ContactModel GeneralContact { get; set; }
}

public class ContactModel:ILinkToEntity<Contact>
{
    [MaxLength(200)]
    [Required]
    public string Name { get; set; }
}
```

The Generic Service is failed to creating the Customer from Customer Dto as the nested property is not supported yet.
```csharp
 var cus = new CustomerDto { Name = "New Name", GeneralContact = new ContactModel { Name = "Duy" } };
service.CreateAndSave<Customer>(cus);
```
Expected: The tested Dto properties shall be transformed to entities by loading the entities from database.

Hope the Generic Service will support nested Dto for creating and updating soon in future.

**Comment by JonPSmith** [comment]
Hi @baoduy,

This isn't a GenericServices issue, but an AutoMapper issue. For reverse mapping like this AutoMapper needs some configuration, which you need to provide via a `PerDtoConfig<TDto, TEntity>` config class ([link to docs about this class](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#perdtoconfigtdto-tentity---optional-configuration-for-a-specific-dto)). 

I added a unit test to check this out and it can be done. Here are the links to the DTOs and the unit test code. The `InContactAddressConfig` is the the one you need to look at, as that contains the AutoMapper config you need (plus a link to AutoMapper's documentation on Reverse Mapping):
#### DTOs and config
- [InContactAddressDto](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/Dtos/InContactAddressDto.cs)
- [InAddressDto](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/Dtos/InAddressDto.cs)
- [InContactAddressConfig](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/Configs/InContactAddressConfig.cs) - this is the important addition
#### Unit test
- [TestNestedInDtosIssue13](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/UnitTests/GenericServicesPublic/TestNestedInDtosIssue13.cs)
