### ISSUE TITLE
Explicitly Calling Services and Injecting AutoMapper

### ISSUE THREAD

**Issue by NickBeukema** [JonPSmith/EfCore.GenericServices#15]
Hello,

I've been experimenting with your GenericServices platform and so far am really liking it. I like the separation it enforces between data models, services, dtos, and controllers. I do have one concern going forward with it:

The resolving of service methods happens at run-time, and gives little to no visibility to where that method is. This isn't a problem on a small scale, but once the application scales I foresee an issue debugging this.

I've somewhat concocted a solution for this, by providing all services through DI and just injecting the desired service(s) into the controller that will be utilizing it. It's a little more work, but I believe this will allow for better visibility into the connection between the controller and service.

Anyways, to my question. I am a huge fan of the auto-mapping core models to DTOs and back. I'm obviously missing out on that benefit by taking out the auto-resolution of service methods. I've looked into how you're utilizing AutoMapper within your configuration step, and wondered: 

**Is there a suggested way to gain access and dependecy inject the AutoMapper instance that you're configuring at startup that you setup the `ILinkToEntity` objects with?**

Giving access to this AutoMapper instance will allow for me to map to and from DTOs within my services and hopefully be the last piece to this puzzle. Thanks for your work and your blog posts, they're very insightful and have been great to read.

**Comment by JonPSmith** [comment]
Hi @NickBeukema,

Well, that is interesting. I'm planning to add a `ProjectTo` method to the library to solve issue #10 over Christmas, but it won't do the reverse mapping you want. 

I think the reverse mapping isn't useful enough to add that feature, but it is very easy to access the AutoMapper mappings, as its public in the the registered `IWrappedConfigAndMapper` instance - see the interface definition [here](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/GenericServices/PublicButHidden/WrappedConfigAndMapper.cs).

Have a look at issue #10 for some code.

I'll leave this open until the `ProjectTo` method is added.

**Comment by NickBeukema** [comment]
Fantastic, I'll be eagerly awaiting.

**Comment by JonPSmith** [comment]
> The resolving of service methods happens at run-time, and gives little to no visibility to where that method is. This isn't a problem on a small scale, but once the application scales I foresee an issue debugging this.

Have a look at the section article [Organising your CRUD code](https://www.thereformedprogrammer.net/is-the-repository-pattern-useful-with-entity-framework-core/#organising-your-crud-code) in my article "Is the repository pattern useful with Entity Framework Core?". This shows the pattern I have developed to make it easy to know where associated methods are.

> I've somewhat concocted a solution for this, by providing all services through DI and just injecting the desired service(s) into the controller that will be utilizing it.

You may like to look at an example of way I call GenericServices in a Controller in my [EfCore.GenericServices.AspNetCore ExampleWebApi](https://github.com/JonPSmith/EfCore.GenericServices.AspNetCore/blob/master/ExampleWebApi/Controllers/ToDoController.cs). Notice how I use `[FromServices]` to inject the service. I use this approach a lot.

**Comment by JonPSmith** [comment]
Hi @NickBeukema,

I have created a preview version of EfCore.GenericServices 2.0.0-preview001 which contains code that allows you to put a pre-query in a projection. Have a look and see if it works for you and let me know. Then I will release it.

**Comment by JonPSmith** [comment]
Hi @NickBeukema,

I think there are three methods/patterns already in EfCore.GenericServices already. I list them with the most applicable first:

1. The `ProjectFromEntityToDto` command takes in a function. This means you can write any code you like in this, as long as to return an IQueryable<TEntity> result.
2. The [PerDtoConfig<TDto, TEntity>](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#perdtoconfigtdto-tentity---optional-configuration-for-a-specific-dto) which allows you to modify the mapping, which I think is close to what you want.
3. Alternatively, the the Wiki page [BeforeDisplay-BeforeSave](https://github.com/JonPSmith/EfCore.GenericServices/wiki/BeforeDisplay-BeforeSave) I show a pattern that allows you to add/modify data in your DTO before display.

**Comment by EddieDL** [comment]
@JonPSmith The ProjectFromEntityToDto works great, but I can't get some things to work at all.

1.  **Reverse of `ProjectFromEntityToDTO`:** I need the ability to do a `ProjectFromDTOtoEntity`. Initially I thought I could just use `ProjectFromEntitytoDTO` and just send reverse the types. I found that you specifically use `_configAndMapper.MapperReadConfig` which won't work when we want to use `PerDtoConfig` to configure a custom `AlterSaveMapping`. I think my preference would be to just have `Project<T, LinkToEntity<T>>` and `Project<LinkToEntity<T>, T>`. But I can see reasons to be more verbose.
2. **Single Entity Mapping:** I know you have said there are alternatives already available to accomplish this, but I can't figure out how to get them to work. The one that seems to be the most appropriate would be to use the `IWrappedConfigAndMapper`. However, It doesn't appear to work properly.  Below is what I did. Maybe I just need to do this differently and can create my own helper method to make it easy.
```
public class MyService : StatusGenericHandler, IStatusGeneric {
  protected readonly Mapper IWrappedConfigAndMapper;
  protected readonly MyContext Context;
        
  public MyService(MyContext context, IWrappedConfigAndMapper mapper)
  {
    Context = context;
    Mapper = mapper;
  }

  public async Task<ProjectDTO> CreateProject(ProjectCreateDTO projectCreateDTO)
  {
    var newProject = Mapper.MapperSaveConfig.CreateMap().Map<Project>(projectCreateDTO);
    Context.Projects.Add(newProject);
    await Context.SaveChangesAsync();
    return Mapper.MapperReadConfig.Map<ProjectDTO>(newProject);
  }
}
```
The result is that there are unmapped members (PK Column primarily). While the same functionality works fine when using `var newProject = Service.ProjectFromEntityToDto<ProjectCreateDTO, Project>(p => (new ProjectCreateDTO[] { project }).AsQueryable()).FirstOrDefault();`

**Comment by JonPSmith** [comment]
Hi @EddieDL,

I didn't implement the `ProjectFromDTOtoEntity` method because it means you are bypassing GenericServices, which is what your code shows. If you are calling EF Core directly then all you need is access the AutoMapper mappings inside GenericServices, which you are doing.

Basically what you are doing to access the AutoMapper mappings in GenericServices is correct, so there is a bug somewhere. I take it that the problem is in the line
```
return Mapper.MapperReadConfig.Map<ProjectDTO>(newProject);
```
Here are my comments that might help you find it:
1. Firstly you should be using `CreateMapper()`, not `.CreateMap()` which [is obsolete](https://stackoverflow.com/questions/36398318/automapper-mapper-createmaptsource-tdestination-is-obsolete).
2. I also I notice that you don't have a `.CreateMapper()` on the line that fails. Not sure if that will fix it, but worth a try. 

I can also tell you that `ProjectFromEntityToDto` uses `ProjectTo<T>`, not `Map<T>`, as that converts into LINQ. If that works then it does suggest that points 1 or 2 are your problem.

*See this [unit test](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/UnitTests/Libraries/TestAutoMapper.cs) on how I access the mappings inside GenericServices.*

**Comment by JonPSmith** [comment]
Hi @EddieDL,

Just wanted to check back to see if you solved your problem. I hope so.

**Comment by JonPSmith** [comment]
Hi @EddieDL,

OK. Lots of things here but the key thing you said was:

> we are not just using the standard GenericServices approach...

If GenericServices doesn't work for you then that's fine, but I think you would be better off using AutoMapper directly. I wrote an article [Building high performance database queries using Entity Framework Core and AutoMapper](https://www.thereformedprogrammer.net/building-efficient-database-queries-using-entity-framework-core-and-automapper/) which will talk you though using AutoMapper directly.

PS. The unit test you show won't pick up the PerDtoConfig because that isn't part of AutoMapper. To get that you need to use GenericServices - see [Unit testing your code](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Unit-testing-your-code) in the GenericService Wiki docs.

**Comment by EddieDL** [comment]
@JonPSmith 

Thanks for the feedback, this is a great discussion. 

I want to clarify what I mean when I said:

> not using the standard GenericServices

We like and want to use many of the facilities of what I think of as GenericServices (`WebApiMessageAndResult`, `IStatusGeneric`, `ILinkToEntity<T>`, `StatusGenericHandler`, etc.). Where we have struggled is specifically with the `ICrudServices` and how it abstracts away everything. To the point where developers and the compiler doesn't really know what is going on. As an example: If you have a custom method you want to execute, you have to use `_service.UpdateAndSave(Data, "UpdatePublishedOn")`.

Perhaps we were naive in thinking ICrudServices isn't required to benefit from the other features. Are you at all interested in supporting scenarios where someone doesn't want to use ICrudServices? We really like what you have created and want to understand and help to improve it.

I would love to hear your thoughts about our struggle. Is this something you have heard before? Should we be looking at this differently?

PS. I haven't had a chance to review all of the references you mentioned, but I am working on it.

**Comment by JonPSmith** [comment]
@EddieDL,

I'm glad you like some of the support code I have build for GenericServices (I have a very similar set in my GenricBizRunner). The part you like are support code I have developed and enhanced over many years - you can find my original [GenericLibsBase](https://www.nuget.org/packages/GenericLibsBase/) which I built in early 2014. As such I suggest you copy those files you find useful and make your own, private library. 

> Are you at all interested in supporting scenarios where someone doesn't want to use ICrudServices?

There is a cost for people to learn how to use EfCore.GenericServices and EfCore.GenericBizRunner so all my efforts are on making that simple to use. There is also a cost for me to support these libraries. Therefore I am very careful as to what I add, and what I support. 

The focus of GenericServices is the ICrudServices and always well be, so my answer is no, I don't want to support usages that don't use ICrudServices as it's off-topic for me. That doesn't mean you can't use/copy the support parts, but I won't be changing them or adding any more docs other than what is there.
