### ISSUE TITLE
The class X has 0 primary keys. I can't handle that.

### ISSUE THREAD

**Issue by philipweiser** [JonPSmith/EfCore.GenericServices#16]
Hello Jon,

I have a Query Type included in my DbContext, and I run into this error, "The class X has 0 primary keys. I can't handle that."  Is there a way to mark the query type so GenericServices skips it when initializing?

**Comment by JonPSmith** [comment]
Thanks @philipweiser,

I didn't know that! Thanks for letting me know. Your timing is perfect as I have arranged a break over Christmas from my clients to write some articles and work on a few issues in my library. I will add this one to the list.

I will leave it open until I have dealt with it.

**Comment by JonPSmith** [comment]
Hi @philipweiser,

I have created a preview version of EfCore.GenericServices 2.0.0-preview001 which contains code that fixes the problem with DbQuery types. Have a look and see if it works for you and let me know. Then I will release it.
