### ISSUE TITLE
How to register one to many owned types

### ISSUE THREAD

**Issue by philipweiser** [JonPSmith/EfCore.GenericServices#17]
Is it possible to register a one-to-many relationship of owned types?  When I try to register the class, GenericServices throws an error when it cannot find a PK on the owned type.

**Comment by JonPSmith** [comment]
Have a look at https://docs.microsoft.com/en-gb/ef/core/what-is-new/ef-core-2.2#collections-of-owned-entities.

**Comment by tesnep** [comment]
Your latest version is compiled to EF Core 2.1.

**Comment by JonPSmith** [comment]
That isn't a problem. NuGet packages allow for you using it with other NuGet packages that are above the ones the library was built with (see [NuGet Versioning](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards)). So, if you load EF Core 2.2 then that version will be used by the library.

I'm doing this myself as I'm looking at CosmosDb in EF Core 2.2
