### ISSUE TITLE
Use of Service Classes

### ISSUE THREAD

**Issue by tesnep** [JonPSmith/EfCore.GenericServices#19]
Hi @JonPSmith,
Can you please clarify how you are injecting (if you are even using) the Service interfaces inside the ServiceLayer/HomeController? 

`namespace ServiceLayer.HomeController
 {
    public interface IListBooksService
    {
        Task<IQueryable<BookListDto>> SortFilterPage
            (SortFilterPageOptions options);
    }
}`

All I see is you're referencing ICrudServices in your PageModel classes. You are not using any of these interfaces.

` public class IndexModel : PageModel
  {
        private readonly ICrudServices _service;
        public IndexModel(ICrudServices service)
        {
            _service = service;
        }`

I noticed the same in your other repo JonPSmith/EfCore.GenericServices.AspNetCore where in your Api Controller you are injecting ICrudServices or ICrudServicesAsync. You're not using any other service.

`
public async Task<ActionResult<WebApiMessageAndResult<TodoItemHybrid>>> GetSingleAsync(int id, [FromServices]ICrudServicesAsync service)
        {
            return service.Response(await service.ReadSingleAsync<TodoItemHybrid>(id));
        }
`

My guess is these are examples for a separate article you've written.

**Comment by JonPSmith** [comment]
Hi @tesnep,

Yes, you are right. I wrote an article that compared hand-coded versions to using CrudServices. I don't call the hand-coded code anywhere. Sorry if that was confusing - I write so many articles that I lose track myself!
