### ISSUE TITLE
problem building RazorPageApp project.assets.json file not found

### ISSUE THREAD

**Issue by githubfanster** [JonPSmith/EfCore.GenericServices#2]
Hello! Just downloaded this library to check it out.

I downloaded the zip file, then double-clicked on the .sln file.

i'm using Visual Studio 2017 Community Edition, my dotnet.exe and sdk version is 2.1.300.

this is the build error i'm getting:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Assets file 'F:\jonsmith\EfCore.GenericServices-master\RazorPageApp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	RazorPageApp	C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
 i haven't encountered this problem before. any tip on a workaround?

doing a "dotnet restore" or "dotnet build" did not work.

wonder if i need to "update" project code to 2.1 ??

contents of RazorPageApp.csproj

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.1" />
    <PackageReference Include="EfCore.TestSupport" Version="1.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataLayer\DataLayer.csproj" />
    <ProjectReference Include="..\GenericServices.AspNetCore\GenericServices.AspNetCore.csproj" />
    <ProjectReference Include="..\ServiceLayer\ServiceLayer.csproj" />
  </ItemGroup>
</Project>

**Comment by JonPSmith** [comment]
Hi @githubfanster,

Yep, I haven't updated my libraries to NET Core 2.1 yet. It's on my to do list but I'm on a contract too. I'll let you know when its done.

**Comment by githubfanster** [comment]
thank you for replying.
i was able to get the first page up and running and the sorting semed to have worked.
i deleted the test and benchmarking projects, then updated target frameworks all to 2.1, then nuget updated any packages that had newer versions -- not just ef core stuff but also autofac etc. also, for the one or two projects that had efcore.genericservices dlls, i removed those dlls, and just pointed to the GenericServices project (did i make the right call for this last step?) 

i'll try to play around with the code some more to see if i missed anything, but hopefully i've covered all bases.

thank you for your book (which i've bought early on) and your work.

any chance u might want to write a book on just Razor Pages (and not the usual MVC stuff) after you're done with your current book?  :-)

**Comment by JonPSmith** [comment]
NET Core versions released on NuGet:

* https://www.nuget.org/packages/EfCore.GenericServices/
* https://www.nuget.org/packages/EfCore.GenericServices.AspNetCore/

Along with my other libraries like https://www.nuget.org/packages/EfCore.TestSupport/  which have also been updated.
