### ISSUE TITLE
Order and Take are evaluating locally

### ISSUE THREAD

**Issue by MartijnSchoemaker** [JonPSmith/EfCore.GenericServices#23]
I've an issue with a query that's using OrderBy and Take that's evaluating locally instead of in SQL. Probably I'm doing things wrong, hope you can help me out.

My Entities are:
```
public class Message 
    {
        public int Id { get; set; }
        public DateTime DateSent { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public virtual IEnumerable<MessageUser> Users { get; set; }
    }

public class MessageUser 
    {
        [Key]
        public int Id { get; set; }
        public int MessageId { get; set; }
        public virtual Message Message { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
        public DateTime? DateRead { get; set; }
        public DateTime? DateDeleted { get; set; }
    }
```

My DTOs look like this:
```
public class MessageUserDto : ILinkToEntity<Data.Models.MessageUser>
    {
        public int Id { get; set; }
        public virtual MessageDto Message { get; set; }
        public string UserId { get; set; }
        public DateTime? DateRead { get; set; }
        public DateTime? DateDeleted { get; set; }
    }

 public class MessageDto : ILinkToEntity<Data.Models.Message>
    {
        public DateTime DateSent { get; set; }
        public string Text { get; set; }
        public string Subject { get; set; }
        public IEnumerable<string> UserIds { get; set; }
    }

```

When I query via DbContext everything works fine:
```
var mesesages = _dbContext.MessageUser
                    .Where(m => m.UserId == user.Id && m.DateDeleted == null)
                    .OrderByDescending(m => m.Message.DateSent)
                    .Take(3)
                    .ToList();
```

This generates this SQL:
```
SELECT TOP(@__p_1) [m].[Id], [m].[CreatedBy], [m].[DateCreated], [m].[DateDeleted], [m].[DateRead], [m].[DateUpdated], [m].[MessageId], [m].[UpdatedBy], [m].[UserId]
FROM [MessageUser] AS [m]
INNER JOIN [Message] AS [m.Message] ON [m].[MessageId] = [m.Message].[Id]
WHERE ([m].[UserId] = @__user_Id_0) AND [m].[DateDeleted] IS NULL
ORDER BY [m.Message].[DateSent] DESC
```

But when I query via ICrudServices / DTOs the ORDER BY and TOP are not in the SQL:
```
var messages2  = _crudServices.ReadManyNoTracked<MessageUserDto>()
                    .Where(m => m.UserId == user.Id && m.DateDeleted == null)
                    .OrderByDescending(m => m.Message.DateSent)
                    .Take(3)
                    .ToList();
```

This generates this SQL:
```
SELECT [dtoMessageUser].[MessageId], [dtoMessageUser.Message].[DateSent], [dtoMessageUser.Message].[Subject], [dtoMessageUser.Message].[Text], [dtoMessageUser].[DateDeleted], [dtoMessageUser].[DateRead], [dtoMessageUser].[Id], CASE
    WHEN [dtoMessageUser].[MessageId] IS NULL
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END, [dtoMessageUser].[UserId]
FROM [MessageUser] AS [dtoMessageUser]
INNER JOIN [Message] AS [dtoMessageUser.Message] ON [dtoMessageUser].[MessageId] = [dtoMessageUser.Message].[Id]
WHERE ([dtoMessageUser].[UserId] = @__user_Id_0) AND [dtoMessageUser].[DateDeleted] IS NULL
```

This is the warning I get:
```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'orderby IIF((Property([dtoMessageUser], "MessageId") == null), null, new MessageDto() {DateSent = [dtoMessageUser.Message].DateSent, Subject = [dtoMessageUser.Message].Subject, Text = [dtoMessageUser.Message].Text}).DateSent desc' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Take(__p_1)' could not be translated and will be evaluated locally.
```

Querying on the entity itself via CrudServices does work:
```
var messages2  = _crudServices.ReadManyNoTracked<MessageUser>()
                    .Where(m => m.UserId == user.Id && m.DateDeleted == null)
                    .OrderByDescending(m => m.Message.DateSent)
                    .Take(3)
                    .ToList();
```

**Comment by JonPSmith** [comment]
I can see that. If you think about it you are asking EF Core to order on a value that hasn't yet been read in (it's complicated, but the DTO causes the SQL to put the data in a variable). 

Thankfully there is a solution in the method [`ProjectFromEntityToDto`](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Read#projectfromentitytodtotentitytdtopredtolinqquery), which allows you to add LINQ prior to the mapping. I'm pretty sure that will fix things.

**Comment by MartijnSchoemaker** [comment]
Thanks for your answer. This solution is working. But there's one disadvantage with this solution. 
CrudServices are used in the presentation layer. In this layer I should only know about DTOs, not about the data entities. 

What's your thought on this?

**Comment by JonPSmith** [comment]
Firstly good, that was the fix - if you want to known why you couldn't do that read section 2.5.2 (page 45) as to why.  I will close this issue as its not a problem in GenericServices.

Here are my thoughts on your more general issue of not having any access to the entity classes in your presentation layer.

1. Does it matter? For some small entity classes I load them directly, so my presentation code has to know about entity classes anyway. (NOTE: GenericServices can read/write entity classes directly).
2. Build our own query object/service using EF Core inside your ServiceLayer (or wherever you define your DTOs). This fits my approach of "use GenericServices for simple CRUD, but if it gets more complicated create your own service using EF Core directly".
3. You *should* be able to add the LINQ commands for your `Message.DateSent` mapping into the AutoMapper config. That *should* allow EF Core to build the correct query (I have done something like this and it worked).
