### ISSUE TITLE
DTO Not Registered as Valid CrudServices DTO

### ISSUE THREAD

**Issue by Spinarooni** [JonPSmith/EfCore.GenericServices#24]
```
NullReferenceException: The class ClassDTO is not registered as a valid CrudServices DTO/ViewModel. Have you left off the ILinkToEntity interface?
GenericServices.Internal.Decoders.DecodedDataCache.GetDtoInfoThrowExceptionIfNotThere(Type dtoType)
```

I have verified that the DTO does have the ILinkToEntity interface implmeneted with the corresponding entity.  Any other things I can check?  I'm out of ideas at this point.

**Comment by Spinarooni** [comment]
I figured out the issue.  I had specified the wrong assembly in the services registration.

`services.GenericServicesSimpleSetup<DbContext>(Assembly.GetAssembly(typeof(AssemblyWithDTO)));`

**Comment by JonPSmith** [comment]
👍
