### ISSUE TITLE
Updating nested DTO's fails with exception

### ISSUE THREAD

**Issue by bleissem** [JonPSmith/EfCore.GenericServices#25]
Hi @JonPSmith ,
i've been off a few days and didn't response.
I just updated 
https://github.com/bleissem/TestNestedInDtosIssue13
and adjusted some things to avoid the automapper errormessage.
I think the automapper related errors are now gone.
I also include the GenericServices Code to be able to show you exactly when the test fails and when it does not fail.

For the test:
TestCallControllerMethodDoesNotWorkOk
now the test still fails but this time with:
Message: Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
---- Microsoft.Data.Sqlite.SqliteException : SQLite Error 19: 'UNIQUE constraint failed: AddressNotOwned.Id'.
This is because when updating an entity there are no navigation properties beeing loaded.

In commit [46c088560e313f5c63fd0ed56d90fd69888eabe5](https://github.com/bleissem/TestNestedInDtosIssue13/commit/46c088560e313f5c63fd0ed56d90fd69888eabe5)
I modified the function CreateMapper.ReturnExistingEntity in GenericServices so that updating actually works and the unit test passes.
However the unit test: TestCallControllerMethodDoesNotWorkOk fails when using the original code from GenericServices.
as seen in commit [95287da18ed115215df73896b90a71668073090e](https://github.com/bleissem/TestNestedInDtosIssue13/commit/95287da18ed115215df73896b90a71668073090e)

_Originally posted by @bleissem in https://github.com/JonPSmith/EfCore.GenericServices/issues/21#issuecomment-471498331_

**Comment by bleissem** [comment]
Hi @JonPSmith,
it seems to be that I can not reopen an issue, so I just open up a new issue and took my last message from #21 

Regards
Alex B.

**Comment by JonPSmith** [comment]
Hi @bleissem,

Sorry, but I don't have the time to debug your specific problem. This is a open-source project that I do in my spare time (?!). I'm pretty sure its a problem with your database/query setup (see my comments about track and untracked entity updates) - that's why you are getting the unique constraint error. Try using a SQL database - it gives you more info on what is wrong.
