### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by malfonso0** [JonPSmith/EfCore.GenericServices#3]
hi jon. not sure if i should write to you here.. or in your blog.. sorry in advance.

I love your library/framework.. i am starting in ASP.NET Core... and the dbcontext/repo/UoW/Service didnt work in my mind.. i finally found your blog and fall in love.

I am starting using the EFCoreGenericServices.. and would like to know what can i do for the following cases

1) Service with and without async: You made the CrudService And CrudServiceAsync. What can i do to Implement a CRUDServiceSyncandAsync ( or something like that).

2) How are you handling ConcurrencyExceptions? All my entities derive from BaseEntity, wich implements a TimeStamp property.
I am trying to capture this, using two browsers... but i am unable of getting an error

**Comment by JonPSmith** [comment]
Hi @malfonso0,

Sorry for the delay in replying - I was travelling. I am glad you found this library useful. Here are my answers to your questions:

1. You can choose either the sync or async version of the library for whatever action you are doing. In ASP.NET Core you should use [dependency injection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1) to obtain a instance of the CrudService/CrudServiceAsync to use. It is unlikely you will what both sync and async within an ASP.NET Core application. But if you really need both then you can create an instance of sync and async and call the appropriate one.
2. EFCore.GenericServices doesn't handle ConcurrencyExceptions, but you should still get a `DbUpdateConcurrencyException` if there is a concurrency issue, as that is handled by EF Core. Note that it s very hard to cause concurrency issues manually with two browsers - you can see the unit tests I use for my book [Entity Framework Core in Action](http://bit.ly/2m8KRAZ) via [this link](https://github.com/JonPSmith/EfCoreInAction/blob/Chapter08/Test/UnitTests/DataLayer/Ch08_Concurrency.cs#L129-L157).

Once you have got concurrency exceptions then you can wrap calls to the CrudService/CrudServiceAsync library with a try/catch, which will allow you to manage concurrency issues.
```c#
try
{
   //... call CrudService/CrudServiceAsync method
}
catch (DbUpdateConcurrencyException ex)
{
   //... handle any ConcurrencyExceptions
}
```

**Comment by malfonso0** [comment]
Jon, thanks for the reply.
On 1.. OK.
On 2.. i have found that using the CRUDServices directly with a Entity throws the dbconcurrencyexception, but using it with a DTO it doesnt throw it.

i Have made a simple example. Asimple db entity, with ID, NAME, Friends ( collection of friends) and Rowversion(Timestamp)
a DTO, almost the same, without Friends and with FriendsCount. Just to practice i made the DtoConfig. All works nice.

To test, i Open  Chrome and a IE browsers and go to edit the same entity. and make some changes
First i save the IE (for example).. and goes ok.. and its ok.
Then i save the Chrome tab.
IF i used the dbEntity.... i got the dbconcurrencyexception. If i used the dto.. the save continues. and value is overwritten in sql

thanks for your time.

**Comment by JonPSmith** [comment]
Hi @malfonso0,

Let me explain the difference between the entity and DTO versions of the `UpdateAndSave` method in the EFCore.GenericServices library.

1. **Entity version**: This writes out the entity that you give it. If you passed the entity data via the HTTP request then it will use the EF Core `Update` method.
2. **DTO version**: This will read read in the entity from the database, copy in the properties in the DTO that aren't marked as `[ReadOnly(true)]` and *if any properties have changed* it will update the database.

I don't have access to your code so I don't know what you are doing. One idea comes to mind - the window for a concurrency issues is different in the two examples: In the entity version it is the time from the GET request to the POST request. In the DTO version it is very small, just the few milliseconds between the read and the update.

**Comment by JonPSmith** [comment]
Hi @malfonso0,

Just to let you know that I have added the `SaveChangesExceptionHandler` feature, which allows you to capture and handle a exception when GenericServices calls `SaveChanges`. I have written [an article](https://www.thereformedprogrammer.net/entity-framework-core-validating-data-and-catching-sql-errors/) about it.

PS. Initially I set this up to only handle `DbUpdateException` but I extended it so you can now catch any exception because of your request. I hope it helps.
