### ISSUE TITLE
Disabling errors on Read no result

### ISSUE THREAD

**Issue by tesnep** [JonPSmith/EfCore.GenericServices#4]
Is there is way to disable errors on CrudServices.Read()? The reason I ask is I have to perform other CrudServices actions like CreateAndSave() on other entities and the IsValid property will not allow this to happen. I need to say "this is perfectly fine if you do not find any data" . 

A use case is I am checking if an employee exists before deciding whether I want to send a duplicate error message or insert. If I cannot find, it sets IsValid to true and I can no longer perform the save.

**Comment by tesnep** [comment]
I ended up remvoing the lines of code that add to errors in CrudServices and CrudAsyncServices for my local code. I've now make use of your library in two projects and about to make use of it in a third one. At some point I am going to buy you 10 coffees. Great work!

**Comment by tesnep** [comment]
I bought you the coffees for now.

**Comment by JonPSmith** [comment]
Hi @tesnep, 

See [release 1.2.3] of GenericServices. It now has a configuration property called `NoErrorOnReadSingleNull` that allows you to turn off errors on null ReadSingle/Async calls. 

See [the configuration docs](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Configuration-options#3-readsingle-and-nulls) for more info on this feature, plus the [unit tests](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/UnitTests/GenericServicesSetup/TestReadSingleNull.cs).
