### ISSUE TITLE
QueryTrackingBehavior.NoTracking and Updates

### ISSUE THREAD

**Issue by andreqb** [JonPSmith/EfCore.GenericServices#44]
Hi @JonPSmith, I am running into an issue/feature :) with this library.  When I wireup my DbContext in startup with the `QueryTrackingBehavior.NoTracking` then calling subsequent Update methods on the CrudServices nothing gets updated which makes sense.  If this is the intent can there be a something in GenericStatus that tells us nothing was affected or indicating the NoTracking status?

**Comment by JonPSmith** [comment]
Hi @andreqb, 

Working with `QueryTrackingBehavior.NoTracking` is a unusual approach and I decided not to add checks in the code as it hit too many places. I have updated the [update documentation](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Update) though.

**Comment by andreqb** [comment]
@JonPSmith  thanks for having a look. When. I do reporting stuff I usually set this propertyfor performance reaaons. I suppose using a different context with the default behavior would work.
