### ISSUE TITLE
Scanning DTOs in Assembly with Multiple Contexts Fails

### ISSUE THREAD

**Issue by CSorel-Catalyte** [JonPSmith/EfCore.GenericServices#45]
I have a data model assembly that contains all of my entities and dtos. It has multiple contexts, for which some of my entities/dtos are associated to each.

I have multiple APIs each of which may only use one of several contexts.

When I call 
```
services.ConfigureGenericServicesEntities(typeof(UserDbContext))
                .ScanAssemblesForDtos(Assembly.GetAssembly(typeof(CreateAPUserDto)))
                .RegisterGenericServices();
```

I get the following error because it is finding dto's for the other contexrt

> Scanning redacted.DataModel>ChangeAuditEventStatusDto: The DTO/ViewModel class ChangeAuditEventStatusDto is linked to a entity class AuditEvent, but I couldn't find that class in the application's DbContext(s) you gave me to scan

Edit: If I add the other contexts to the ConfigureGenericServicesEntities method, I get past it, but then It fails with:

> 'You provided the a DbContext called AuditingDbContext, but it doesn't seem to be registered, or is a DbContext. Have you forgotten to register it?'

I don't want to have to register all of the db contexts in every API, just the ones I need for that API.

**Comment by JonPSmith** [comment]
What I think you are saying is:
1. You have multiple DbContexts
2. You have multiple DTOs, which are used in one of the DbContexts, i.e. your comment

> I have multiple APIs each of which may only use one of several contexts.

On the first point, multiple DbContexts, you need to register ALL the DbContexts in one call. I show that in the [Installing GenericServices with DI in ASP.NET Core](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Installing-GenericServices#registering-genericservices-with-di-in-aspnet-core) at the end under "Advanced notes". That means the call to `ConfigureGenericServicesEntities` in the issue needs all the DbContexts in it, no just one. 

On point 2, that should be fine. As long at the DTO is linked to an entity class in one of the DbContexts you register then it will work.

**Comment by CSorel-Catalyte** [comment]
Not exactly. I had a single assembly with multiple contexts and multiple entities.
The entities were only added to the relevant context.

In my APIs, I only add the necessary contexts. However, because there were DTOs in that assembly that were not included in any loaded context in the API, I get an error.

> Scanning redacted.DataModel>ChangeAuditEventStatusDto: The DTO/ViewModel class ChangeAuditEventStatusDto is linked to a entity class AuditEvent, but I couldn't find that class in the application's DbContext(s) you gave me to scan

I wanted to have a single assembly for all of my data model but not have to load up all contexts in every API. I refactored it so that each context and relevant entities were in separate assemblies to move past this.

**Comment by JonPSmith** [comment]
You must include all the DbContext and all the assemblies that contains your DTOs in the initial `ConfigureGenericServicesEntities`  (note: you can provide multiple assemblies to to be scanned).

If you are doing that and still getting an issue then it could be that you used a IlinkToEntity with a Owned Type (Owned Types aren't always mapped to the database).

**Comment by CSorel-Catalyte** [comment]
I don't think you're understanding my issue. There are valid cases where I want to have multiple contexts and DTOS in one assembly but not use them all in one web project. Specifically a shared data model across multiple microservices that may need to interoperate.

The issue is not that I'm not including all assemblies, it's that unless I load every context in the assembly, it yells at me that it can't link up all the DTOs, even though I don't need all of the dtos/contexts in that particular web project.

Scenario:
I have a shared data model project, it has several contexts. It compiles into a single assembly.
AuditingContext handles entities related to auditing
EventContext handles entities related to events
UserContext handles entities related to users & profiles
WebAppContext handles all entities directly related to the web app

Each domain has dtos corresponding to the entities and the actions you can take on them. All Entities and DTOs are separated by namespace.

I have a web app and 3 microservice APIs
Web App needs all 4 contexts
Auditing API needs AuditingContext and EventContext
UserApi needs AuditingContext and UserContext
EventApi needs EventContext

Web App is not a problem because I load up all 4 Contexts
The Auditing API fails unless I include the UserContext and WebAppContext, which I don't need.
The User API fails unless I include the EventContext and WebAppContext, which I don't need.
The EventAPI fails unless I include the AuditingContext, UserContext, and EventContext.

If the ScanAssemblesForDtos(Assembly.GetAssembly(typeof(CreateAPUserDto))) included an optional array of namespace strings, you could specify the namespaces you want it to scan in the assembly and avoid this issue.

I can't imagine I'm the only person with this use case.

**Comment by JonPSmith** [comment]
OK, I get understand now, but that is quite unusual situation. The normal registering approach can't handle that and its so unusual that I don't plan to support it.

You *might* be able to use the [code used for unit testing](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Unit-testing-your-code), which allows you to manually register each DTO, but if you have a lot of DTOs its going to be a pain. Someone who didn't have DI used this approach for their application.
