### ISSUE TITLE
GenericServiceErrorHandler not exist

### ISSUE THREAD

**Issue by Al-Sharif** [JonPSmith/EfCore.GenericServices#48]
I Installed EfCore.GenericServices nuget package, but there's no GenericServiceErrorHandler

**Comment by JonPSmith** [comment]
I'm not sure what you are looking for - what do you mean by `GenericServiceErrorHandler`?

If you are after the `IStatusGeneric`, then its in the NuGet  package [GenericServices.StatusGeneric](https://www.nuget.org/packages/GenericServices.StatusGeneric/).

If you are after the exception handler its in the configuration setup - see [this section](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Configuration-options#3-sql-error-handling) in the GenericServices Wiki which holds the documentaion
