### ISSUE TITLE
Open GenereicServices solution in VS2015 results in error

### ISSUE THREAD

**Issue by Twoleeland** [JonPSmith/EfCore.GenericServices#5]
Hello,

I have following problem with opening the solution in Visual Studio Pro 2015:
![21-08-_2018_10-08-50](https://user-images.githubusercontent.com/1656150/44389257-a62d5b80-a52a-11e8-9a20-4cb61bdb8b62.png)

Somehow the csproj-files are different to the "normal" csproj-files. That's why VS refuses to open the projects of the solution:
![21-08-_2018_10-14-49](https://user-images.githubusercontent.com/1656150/44389424-1a67ff00-a52b-11e8-8007-dbea15859d83.png)

So, how can I open the projects in VS?!

Kind regards

**Comment by JonPSmith** [comment]
Hi @Twoleeland,

NET Core needs Visual Studio 2017 for NET Core - see https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x
