### ISSUE TITLE
EF Core 5.0 Many-To-Many relationships not working

### ISSUE THREAD

**Issue by chrisbbe** [JonPSmith/EfCore.GenericServices#52]
Hi,

At first look, there seem to be issues with the new ManyToMany relationship feature in EF Core 5.0. The relationship mapping table is represented as Dictionary<string, object> in EF causing GenericServices to fail during the registration of entity classes. 

Is this known?

**Comment by chrisbbe** [comment]
One solution is to specify the `.UsingEntity<> `method to make it work, which maybe is good practice in the name of DDD anyway.

[](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many)

**Comment by JonPSmith** [comment]
Hi @chrisbbe,

Yes, EfCore.GenericServices 3.2.2 works with EF Core 2 and EF Core 3 and it doesn't know anything about EF Core 5's property bags used for automatic many-to-many relationships. As you say, the  `.UsingEntity<>` config method to make to a normal entity class works.

Changing EfCore.GenericServices and my other libraries is going to be a big job and i won't start that until I have finished updating my book Entity Framework Core in Action to EF Core 5.

**Comment by JonPSmith** [comment]
Version 5.0.0 handles the new ManyToMany relationship feature in EF Core 5.0.
