### ISSUE TITLE
ArgumentException: Type 'ObserVisionWeb.PaginatedList`1[MyDto]' does not have a default constructor (Parameter 'type')

### ISSUE THREAD

**Issue by Lerseb** [JonPSmith/EfCore.GenericServices#55]
Hi Jon,
Your book and articles are awesome for a beginner like myself.
I am facing the issue in the title and I cannot find the problem because it happen in between the click on the razorpage <input> button and the beginning of the related method in my model (I put a breakpoint but never reached it).
I must be doing something wrong in my GenericServices or maybe AutoMapper setup.
I am using ReadManyNoTracked to populate the PaginatedList with the Dto.
I added parameterless constructors for related DbContext, the Dto and the related Entity with no result.
Using EfCore.GenericServices (3.2.2)
Thanks
Seb

**Comment by Lerseb** [comment]
My apologize, It was an issue with my PaginatedList. I replaced it with a standard List and it is working perfect.
Sorry
Seb

**Comment by JonPSmith** [comment]
Hi @Lerseb,

Glad you found it. It's hard for me to debug this kind of thing from an exception.

One thing I was going to suggest for debugging is to writing the code using EF Core directly. That way you know that its not the library that is causing the problem.

**Comment by Lerseb** [comment]
Thanks Jon
