### ISSUE TITLE
of type 'System.DBNull' to type 'System.DateTime'

### ISSUE THREAD

**Issue by naujoks-stefan** [JonPSmith/EfCore.GenericServices#59]
Hallo Jon,

after reading your book, i was thrilled with your approach. Now I've created a simple project for myself, starts properly. I have an entity with a property of the DateTime? Type. I get the exception:
 An unhandled exception has occurred while executing the request.
      System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.DateTime'.
         at MySqlConnector.Core.Row.GetDateTime(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 358
         at MySqlConnector.MySqlDataReader.GetDateTime(Int32 ordinal) in /_/src/MySqlConnector/MySqlDataReader.cs:line 261

Any idea how I can solve this problem?

**Comment by JonPSmith** [comment]
Hi @naujoks-stefan,

This looks like an EF Core / database issue, not a GenericServices issue. Looks like your database column isn't nullable.
