### ISSUE TITLE
Not compatible with Automapper 11.0.0

### ISSUE THREAD

**Issue by Akku-21** [JonPSmith/EfCore.GenericServices#61]
Hi there,

I just wanted to let you know, that your latest release 5.1.1 is not compatible with Automapper v 11.0.0.

regards Jan

**Comment by JonPSmith** [comment]
What do you mean by "...not compatible with Automapper v 11.0.0"? Does it no compile, or fails when used?

**Comment by Akku-21** [comment]
It compiles but throws in service registration with a
Method not found: 'Void AutoMapper.Profile.ForAllPropertyMaps... Exception.

regards Jan

**Comment by JonPSmith** [comment]
Difficult - AuthoMapper 11.0.0. doesn't support net6 - see [this](https://docs.automapper.org/en/latest/11.0-Upgrade-Guide.html).

Not going to look at that for a while, so use AuthMapper 10.1.1 for now.

**Comment by JonPSmith** [comment]
Hi @Jerrill,

Sorry I missed your comment / PR - I must have been busy around the time an missed this. Sorry about that.

I will updating all my libraries to support NET7 and I will try your PR and see how it goes.

**Comment by JonPSmith** [comment]
Hi @Jerrill,

Version 5.2.0 of this library is out with your PR. Thanks for your help.
