### ISSUE TITLE
Causes application crash when used with Serilog bootstrap logger.

### ISSUE THREAD

**Issue by Dimi1010** [JonPSmith/EfCore.GenericServices#62]
### Description:
When trying to implement a [two-state logger initialization with Serilog](https://github.com/serilog/serilog-aspnetcore#two-stage-initialization) the application builder throws the following exception on build.
```
System.InvalidOperationException: The logger is already frozen.
```

The exception is not thrown when `builder.Services.GenericServicesSimpleSetup<>()` is not called. 
The issue appears to be linked to the DI container being built twice, once in the GenericServices Setup and then in `builder.Build()`.
In the first occasion EF Core obtains a logger from the service collection triggering Serilog.
The issue also appears similar to [another issue on JADNC](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/1082).

### Potential workarounds:
As mentioned in the abovementioned issue, using a null logger factory can suppress the issue at the cost of disabling logging for EF Core.
```
builder.Services.AddDbContext<ApplicationBuilder>(options =>
{
    options.UseLoggerFactory(NullLoggerFactory.Instance);
})
```

### Steps to reproduce:
Created a project repo where the issue can be explored: https://github.com/Dimi1010/EfCoreGenericServicesAndSerilogBootstrapRepo. 
Run the project for reproduction.

### Expected Behavior:
Exception should not be thrown and the app should start normally.

### Actual Behavior:
Exception is thrown.

### Versions Used:
- EfCore.GenericServices version 5.1.1
- ASP.NET Core version 6.0.2
- Entity Framework Core version 6.0.6
- Database provider: In memory
- Serilog.AspNetCore version 5.0.0

**Comment by JonPSmith** [comment]
Hi @Dimi1010,

The change you want me to do isn't trivial and isn't a lot of people asking for this feature. I have others things to do so I'm not going to add this. 

If you can work a way to add your feature works without breaking the current way it works I will look at it. Alternatively you can clone the code and create your own version.

**Comment by Dimi1010** [comment]
Alright, understandable. Closing this issue, but will leave it for the workaround if other people encounter similar problem.
