### ISSUE TITLE
How do you configure an AutoMapper IGlobalFeature?

### ISSUE THREAD

**Issue by kcaswick** [JonPSmith/EfCore.GenericServices#64]
I'm try to add [AutoMapper.Collection](https://github.com/AutoMapper/AutoMapper.Collection), but it requires being set as an IGlobalFeature on the IMapperConfigurationExpression, not in an individual map. I'm not seeing any way to inject configurations into the MapperReadConfig or MapperSaveConfig before it gets sealed.

**Comment by JonPSmith** [comment]
Hi @kcaswick,

When I update GenericServices to support NET7 I will see if there is a way to allow access to creation of the automapper mapping. 

I should say that I don't plan to support the [AutoMapper.Collection](https://github.com/AutoMapper/AutoMapper.Collection) within the GenericServices code as it already quite complex for user to understand (and me to update). If that means that AutoMapper.Collection won't help, then let me know.

**Comment by kcaswick** [comment]
While you're making those updates, it would be nice if you also gave a "official" way to copy the mapper configurations for use outside GenericServices. (Currently I use GenericServices.**PublicButHidden**.IWrappedConfigAndMapper.MapperReadConfig.Profiles to get a list of the configured mappings and apply it to a new MapperConfiguration(), along with some additional mappings.)

I don't believe any direct support for AutoMapper.Colleciton is needed - the entire way I used it was 2 config lines, and then it automatically altered the ordering of all collection mappings.

```C#
                var mapperConfig = new MapperConfiguration(opt =>
                {
                    opt.AddCollectionMappers();
                    opt.UseEntityFrameworkCoreModel<MyDbContext>(Context.Model);
                // ...
```

Since I was unable to use AutoMapper.Collection to fully solve the issue, I did find an alternate solution that turns out not to use it at all. Adding an additional DTO rather than updating the entity seems to have solved the issue.

P.S. The context is that I have a DTO linked to the entity for a non-updatable SQL view, and after the client posts it, use it to update the (standard-style) entities for the underlying tables. I was doing this by reading the table entity, updating it, and saving it, with code similar to:
```C#
var entity = await Svc.ReadSingleAsync<Order>(dto.OrderId);
mapper.Map<SqlViewDto, Order>(dto, entity);
await UpdateAndSaveAsync(entity);
```
This worked for the root object, but not for stuff like `dto.LineItems`, until I used AutoMapper.Collection.

Perhaps I was just taking entirely the wrong approach though, as the alternate solution without AutoMapper.Collection involved creating an additional DTO linked directly to the entity for the underlying table, and changing the above to:
```C#
var writeDto = await Svc.ReadSingleAsync<AdditionalDto>(dto.OrderId);
mapper.Map<SqlViewDto, AdditionalDto>(dto, writeDto);
await UpdateAndSaveAsync(writeDto);
```

**Comment by JonPSmith** [comment]
Hi @kcaswick,

Sorry, but I haven't looked into adding access to the AuthMapper mapping in the new 5.2.0 version. I have eight libraries to update and some are complex, plus I am busy with other things.

**Comment by JonPSmith** [comment]
Hi @kcaswick,

@JonathanQuinth has found a problem in EfCore.GenericServices (see [his PR](https://github.com/JonPSmith/EfCore.GenericServices/pull/67)) and I plan to look at next, which might be is a good time to look at your request.

Looking through your comments it seems that you don't want to use [AutoMapper.Collection](https://github.com/AutoMapper/AutoMapper.Collection), but anything **simple** to do then please send your suggestion.

I don't want to add your solution, but give you access to the place inside the library that you want to inject / change something, rather like the `NameMatcher` or the `SaveChangesExceptionHandler` in the [GenericServicesConfig](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/GenericServices/Configuration/GenericServicesConfig.cs) class.

Please make is simple because I have another project that I need to finish.

**Comment by JonPSmith** [comment]
You never came back so I am closing this issue

**Comment by kcaswick** [comment]
I'm sorry, never saw the email last month that you had commented. 

All that's needed is some way to inject MapperConfigurationExpressions into the the read and write mappings. (If those even need to be separate mappings.)

For example, it could be changed to work like https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L98

or it could just be adding read and write MapperConfigurationExpressions to the IGenericServicesConfig that get run in addition to adding the profiles in https://github.com/JonPSmith/EfCore.GenericServices/blob/master/GenericServices/Setup/Internal/SetupDtosAndMappings.cs#L43

Unfortunately I'm in crunch time on a project right now, so I can't prepare a PR at this time.
