### ISSUE TITLE
Release `V8.0.0` identical to `6.0.0`

### ISSUE THREAD

**Issue by aaron-kruse** [JonPSmith/EfCore.GenericServices#69]
I went to look at the changes between the recent new `V8.0.0` release and the previous `6.0.0` release to see what changed but noticed the [compares](https://github.com/JonPSmith/EfCore.GenericServices/compare/6.0.0...V8.0.0) show the two are identical. Looking closer, I noticed V8.0.0 also says "[3 commits](https://github.com/JonPSmith/EfCore.GenericServices/compare/V8.0.0...master) to master since this release". I'm not entirely familiar with the "release" process from within GitHub, but it looks like the new release was created as of the commit just _before_ the changes intended to be included in the new release (ex. created from 9cfb425937d9c6e7f3267f2f52a59471826b57b5 instead of 2a2f27f3cb575157a7be3d0e634f5481b6ba09fa).

**Comment by JonPSmith** [comment]
I worked out what when wrong. I has the EfCore.GenericServices in my browser already, then I pushed the new changes to GitHub but I forgot to reload my browser. This means when I created a new release it used the old (6.0.0) in the release. When looking at the problem I must have reloaded the browser and then it worked.

Now I know.
